### ISSUE TITLE
Pager Component is not displaying correctly

### ISSUE THREAD

**Issue by jgutta** [wadahiro/griddle-react-bootstrap#2]
Hello!

The pager component is not displaying correctly on my grid.
![screen shot 2016-06-10 at 3 43 26 pm](https://cloud.githubusercontent.com/assets/5608668/15976684/2e580e64-2f22-11e6-8b27-7773ce4ee6a3.png)

I have tried changing those checkboxes (they are static) out to just plain text, but the issue persisted. My griddle usage looks like this:

< GriddleBootstrap
                results={entities}
                columnMetadata={columnMetadata}
                columns={columns}
                bodyHeight={600}
                resultsPerPage={20}
                initialSort="display_name"
                onRowClick={(gridData, vent) => browserHistory.push('/web/publisher/' + gridData.props.data.id)}
                striped={true}
                bordered={true}
                condensed={true}
                hover={true}
            />
I can't find anything that I am doing wrong, and using the standard Griddle component seems to work fine. Thanks in advance for your help!

Edit: I have tried stripping the component down to just the basics, and the display issue persists.

**Comment by wadahiro** [comment]
@jgutta Do you use `griddle-react-bootstrap.css`? If you install this library by `npm` command,  the css file is located in `node_modules/griddle-react-bootstrap/dist` directory.

**Comment by jgutta** [comment]
Looks like I wasn't importing it from the right directory. Thanks!
