### ISSUE TITLE
React.__spread is deprecated

### ISSUE THREAD

**Issue by Marmelatze** [wadahiro/griddle-react-bootstrap#3]
Hi,

I just tried this package with react 15.1.0 and it logs the this warning:

> Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.

According to the linked PR the issue should be gone by recompiling with typescript 1.8.10.

**Comment by wadahiro** [comment]
@Marmelatze Thanks your reporting! I'll rebuild soon.

**Comment by wadahiro** [comment]
I published v0.4.4 to npm registry.

**Comment by Marmelatze** [comment]
Thanks for the fast reply :thumbsup: The warning is gone.
